// ─────────────────────────────────────────────────────────────────────────────
// CITY CONFIGURATION
// Each city contains: map center, zoom level, and environmental anomaly zones
// ─────────────────────────────────────────────────────────────────────────────

export const CITY_CONFIG = {
  mumbai: {
    id: "mumbai",
    label: "Mumbai",
    center: [72.8777, 19.076],
    zoom: 11.5,
    zones: [
      {
        id: "mum-1",
        name: "Dharavi Industrial Corridor",
        coords: [72.8556, 19.0478],
        severity: 91,
        air: 78,
        water: 62,
        land: 44,
        type: "critical",
      },
      {
        id: "mum-2",
        name: "Deonar Waste Complex",
        coords: [72.9275, 19.0425],
        severity: 88,
        air: 85,
        water: 58,
        land: 72,
        type: "critical",
      },
      {
        id: "mum-3",
        name: "Chembur Petrochemical Belt",
        coords: [72.9005, 19.0522],
        severity: 76,
        air: 70,
        water: 42,
        land: 55,
        type: "severe",
      },
      {
        id: "mum-4",
        name: "Versova Creek Estuary",
        coords: [72.8137, 19.1357],
        severity: 64,
        air: 38,
        water: 81,
        land: 28,
        type: "high",
      },
      {
        id: "mum-5",
        name: "Bandra-Kurla Zone",
        coords: [72.8652, 19.0654],
        severity: 46,
        air: 52,
        water: 28,
        land: 18,
        type: "moderate",
      },
    ],
    // Positions relative to simulated map canvas (percentages)
    zonePositions: [
      { id: "mum-1", x: "43%", y: "61%" },
      { id: "mum-2", x: "57%", y: "63%" },
      { id: "mum-3", x: "55%", y: "55%" },
      { id: "mum-4", x: "32%", y: "38%" },
      { id: "mum-5", x: "48%", y: "52%" },
    ],
  },

  bangalore: {
    id: "bangalore",
    label: "Bangalore",
    center: [77.5946, 12.9716],
    zoom: 11.5,
    zones: [
      {
        id: "blr-1",
        name: "Bellandur Lake Catchment",
        coords: [77.6387, 12.9305],
        severity: 86,
        air: 42,
        water: 94,
        land: 36,
        type: "critical",
      },
      {
        id: "blr-2",
        name: "Varthur Wetland Basin",
        coords: [77.7323, 12.9416],
        severity: 74,
        air: 35,
        water: 88,
        land: 44,
        type: "severe",
      },
      {
        id: "blr-3",
        name: "Peenya Industrial Cluster",
        coords: [77.5179, 13.027],
        severity: 79,
        air: 84,
        water: 32,
        land: 48,
        type: "severe",
      },
      {
        id: "blr-4",
        name: "HSR Layout Sector",
        coords: [77.6389, 12.9116],
        severity: 41,
        air: 46,
        water: 28,
        land: 22,
        type: "moderate",
      },
    ],
    zonePositions: [
      { id: "blr-1", x: "58%", y: "65%" },
      { id: "blr-2", x: "72%", y: "60%" },
      { id: "blr-3", x: "34%", y: "38%" },
      { id: "blr-4", x: "57%", y: "72%" },
    ],
  },

  delhi: {
    id: "delhi",
    label: "Delhi",
    center: [77.209, 28.6139],
    zoom: 11,
    zones: [
      {
        id: "del-1",
        name: "Anand Vihar Air Corridor",
        coords: [77.3158, 28.6469],
        severity: 96,
        air: 98,
        water: 42,
        land: 52,
        type: "critical",
      },
      {
        id: "del-2",
        name: "Yamuna Floodplain Sector",
        coords: [77.28, 28.66],
        severity: 89,
        air: 58,
        water: 93,
        land: 68,
        type: "critical",
      },
      {
        id: "del-3",
        name: "Ghazipur Landfill Mass",
        coords: [77.3165, 28.6379],
        severity: 93,
        air: 87,
        water: 62,
        land: 90,
        type: "critical",
      },
      {
        id: "del-4",
        name: "Wazirpur Industrial Hub",
        coords: [77.17, 28.7],
        severity: 82,
        air: 89,
        water: 36,
        land: 46,
        type: "severe",
      },
      {
        id: "del-5",
        name: "Okhla Industrial Estate",
        coords: [77.2831, 28.5475],
        severity: 77,
        air: 76,
        water: 54,
        land: 50,
        type: "severe",
      },
    ],
    zonePositions: [
      { id: "del-1", x: "62%", y: "42%" },
      { id: "del-2", x: "52%", y: "36%" },
      { id: "del-3", x: "63%", y: "44%" },
      { id: "del-4", x: "38%", y: "28%" },
      { id: "del-5", x: "54%", y: "68%" },
    ],
  },
};
